const actionTypes = {
    APP_INITIALIZE: 'APP/INITIALIZE',
    LOGIN_DATA_ENTERED: 'LOGIN/DATA_ENTERED',
    LOGIN_SUCCESS: 'LOGIN/SUCCESS',
    PROVIDER_ADD_NEW_PROVIDER_SELECTED: 'PROVIDER/ADD_NEW_PROVIDER_SELECTED',
    PROVIDER_SAVE_NEW_PROVIDER_SELECTED: 'PROVIDER/SAVE_NEW_PROVIDER_SELECTED',
    PROVIDERS_GET_PROVIDERS_SUCCESS: 'PROVIDERS/GET_PROVIDERS_SUCCESS',
    PROVIDER_SAVE_NEW_PROVIDER_SUCCESSFUL: 'PROVIDER/SAVE_NEW_PROVIDER_SUCCESSFUL',
    PROVIDERS_ROUTE_INITIALIZE: 'PROVIDERS/ROUTE_INITIALIZE',
    SPECIALITIES_GET_SUCCESS: 'SPECIALITIES/GET_SUCCESS',
    WINDOW_RESIZE: 'WINDOW/RESIZE',
    ZONES_GET_SUCCESS: 'ZONES/GET_SUCCESS',
}

export default actionTypes
