const actionTypes = {
    APP_INITIALIZE: 'APP/INITIALIZE',
    LOGIN_DATA_ENTERED: 'LOGIN/DATA_ENTERED',
    LOGIN_SUCCESS: 'LOGIN/SUCCESS',
    LENDER_ADD_NEW_LENDER_SELECTED: 'LENDER/ADD_NEW_LENDER_SELECTED',
    LENDER_SAVE_NEW_LENDER_SELECTED: 'LENDER/SAVE_NEW_LENDER_SELECTED',
    LENDERS_FILTERING_BY_NAME: 'LENDERS/FILTERING_BY_NAME',
    LENDERS_FILTERING_BY_PLAN: 'LENDERS/FILTERING_BY_PLAN',
    LENDERS_FILTERING_BY_SPECIALITY: 'LENDERS/FILTERING_BY_SPECIALITY',
    LENDERS_GET_LENDERS_SUCCESS: 'LENDERS/GET_LENDERS_SUCCESS',
    LENDER_SAVE_NEW_LENDER_SUCCESSFUL: 'LENDER/SAVE_NEW_LENDER_SUCCESSFUL',
    LENDERS_ROUTE_INITIALIZE: 'LENDERS/ROUTE_INITIALIZE',
    SIDEBAR_AUTORIZATIONS_SELECTED: 'SIDEBAR/AUTORIZATIONS_SELECTED',
    SIDEBAR_DASHBOARD_SELECTED: 'SIDEBAR/DASHBOARD_SELECTED',
    SIDEBAR_LENDERS_SELECTED: 'SIDEBAR/LENDERS_SELECTED',
    SPECIALITIES_GET_SUCCESS: 'SPECIALITIES/GET_SUCCESS',
    WINDOW_RESIZE: 'WINDOW/RESIZE',
    ZONES_GET_SUCCESS: 'ZONES/GET_SUCCESS',
}

export default actionTypes
